<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="HelloWorldInterface"
     targetNamespace="http://practice.com/demo/helloword/helloworldinterface"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://practice.com/demo/helloword/helloworldinterface"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="HelloWorldService">
        <plnk:role name="helloworldPortType" portType="tns:helloworldPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://practice.com/demo/helloword/helloworldinterface" location="HelloWorldInterface.wsdl"/>
</wsdl:definitions>
